name: Lint

on:
  push:
    branches-ignore: [main]
    # Remove the line above to run when pushing to master
  pull_request:
    branches: [main]

jobs:
  build:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          # Flag to enable or disable the linting process of the Python language. (Utilizing: pylint) (keep for backward compatibility)
          VALIDATE_PYTHON: false
          # Flag to enable or disable the linting process of the Python language. (Utilizing: black)
          VALIDATE_PYTHON_BLACK: false
          # Flag to enable or disable the linting process of the Python language. (Utilizing: flake8)
          VALIDATE_PYTHON_FLAKE8: false
          # Flag to enable or disable the linting process of the Python language. (Utilizing: isort)
          VALIDATE_PYTHON_ISORT: false
          # Flag to enable or disable the linting process of the Python language. (Utilizing: mypy)
          VALIDATE_PYTHON_MYPY: false
          # Flag to enable or disable the linting process of the Python language. (Utilizing: pylint)
          VALIDATE_PYTHON_PYLINT: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}