name: Lint
# Super-Linter https://github.com/github/super-linter

on:
  push:
    branches-ignore: [main]
    # Remove the line above to run when pushing to master
  pull_request:
    branches: [main]

jobs:
   call-lint:
    uses: jamesbrond/jamesbrond/.github/workflows/lint.yml@main
    secrets:
      token: ${{ secrets.TOKEN }}

# ~@:-]
